openstack_cloud: openstack

openstack_flavors:

  - name: m1.medium
    cloud: "{{ openstack_cloud }}"
    state: present
    vcpus: 1
    ram: 2048
    disk: 20

openstack_images:

  - name: rhel-guest
    cloud: "{{ openstack_cloud }}"
    state: present
    container_format: bare
    disk_format: qcow2
    filename: /tmp/rhel.qcow2

openstack_keypair:

  name: ansible_ssh
  cloud: "{{ openstack_cloud }}"
  state: present
  public_key_file: "{{ ansible_env.HOME }}/.ssh/test_id_rsa.pub"

openstack_networks:
  # Public Facing Network   
  external:
    cloud_name: openstack
    network_name: ext_network
    provider_network_type: flat
    provider_physical_network: datacentre
    subnet_name: ext_subnet
    cidr_network: "192.0.2.0/24"
    state: present
    external: true
    gateway_ip: 192.0.2.254
    admin_state: yes
    ip_version: 4
    enable_dhcp: no
    allocation_pool_start: 192.0.2.150
    allocation_pool_end: 192.0.2.200


  # Private Facing Network   
  internal:
    cloud_name: openstack
    network_name: int_network
    subnet_name: int_subnet
    cidr_network: "172.16.0.0/24"
    state: present
    external: false
    admin_state: yes
    ip_version: 4
    enable_dhcp: yes

  # Public Facing Router connecting the two networks
openstack_routers:
  router:
    cloud_name: openstack
    state: present
    name: router
    network: ext_network
    interfaces: int_subnet

openstack_security_groups: []    
