openstack_cloud: openstack

openstack_flavors:

  - name: m1.medium
    cloud: "{{ openstack_cloud }}"
    state: present
    vcpus: 1
    ram: 2048
    disk: 20

openstack_images:

  - name: rhel-guest
    cloud: "{{ openstack_cloud }}"
    state: present
    container_format: bare
    disk_format: qcow2
    filename: /tmp/rhel.qcow2

