---
- name: OpenStack end to end configuration
  hosts: control
  gather_facts: false
  become: false

  tasks:

    - name: Fetch Instance Info
      os_server_info:
        cloud: openstack
        region_name: regionOne
      register: r_os_servers

    - name: Add host
      add_host:
        name: "{{ item.public_v4 }}"
        group:
          - "{{ item.metadata.group }}"
          - "{{ item.metadata.deployment_name }}"
      loop: "{{ r_os_servers.openstack_servers }}"

- name: Setup Repos
  hosts: load_balancers:database_servers
  gather_facts: false
  become: true
  tags:
    - common

  tasks:

    - name: Copy repo file
      copy:
        src: ../files/open_three-tier-app.repo
        dest: /etc/yum.repos.d/open_three-tier-app.repo

