---
openstack_instances: 
  - instance_name: app1
    group: app_servers
    deployment: dev
    security_group_name: apps

  - instance_name: app2
    group: app_servers
    deployment: dev
    security_group_name: apps

  - instance_name: appdb1
    group: database_servers
    deployment: dev
    security_group_name: db

  - instance_name: frontend
    group: load_balancers
    deployment: dev
    security_group_name: frontend
...
